name: Submit Site to Bing

on:
  push:
    branches:
      - main

jobs:
  submit-to-bing:
    runs-on: ubuntu-latest

    steps:
      - name: Submit URL to Bing
        run: |
          curl -X POST "https://ssl.bing.com/webmaster/api.svc/json/SubmitUrl?apikey=01a54536a9274662bd5670b085d5d9d8" \
          -H "Content-Type: application/json" \
          -d '{"siteUrl":"https://map.zol.hk/","url":"https://map.zol.hk/sitemap.php"}'
